CREATE TABLE IF NOT EXISTS USER_BALANCE (
    user_id VARCHAR(10) NOT NULL PRIMARY KEY,
    available_point BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CHECK (available_point >= 0)
);

CREATE TABLE IF NOT EXISTS POINT_TRADE (
    point_key VARCHAR(5) NOT NULL PRIMARY KEY,
    user_id VARCHAR(10) NOT NULL,
    trade_type VARCHAR(10) NOT NULL,
    amount BIGINT NOT NULL,
    remain_amount BIGINT NOT NULL,
    order_no VARCHAR(255),
    original_point_key VARCHAR(5),
    expire_yn VARCHAR(1) NOT NULL,
    expire_ymd VARCHAR(8),
    status VARCHAR(20) NOT NULL,
    request_id VARCHAR(128) NOT NULL,
    admin_granted_yn VARCHAR(1),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CHECK (amount > 0 AND remain_amount >= 0),
    CONSTRAINT uk_point_trade_request_id UNIQUE (request_id)
);

CREATE TABLE IF NOT EXISTS POINT_DETAIL (
    detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(10) NOT NULL,
    point_key VARCHAR(5) NOT NULL,
    trade_type VARCHAR(10) NOT NULL,
    source_point_key VARCHAR(5),
    target_point_key VARCHAR(5),
    amount BIGINT NOT NULL,
    order_no VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    CHECK (amount > 0)
);
